# -*- coding: utf-8 -*-
"""AI Real Estate Agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rc_-1lxl3Mw1ahrjNXRnDqElIX_BSgIe
"""

# -----------------------------------------------------------------------------
# 0. IMPORTS & CONFIGURATION
# -----------------------------------------------------------------------------
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import joblib

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder, OrdinalEncoder
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Set random seed for reproducibility
np.random.seed(42)


import os
import gc
import zipfile

#1. Load Data

from google.colab import files
print("Please upload your train.csv, test.csv, and sample_submission.csv (optional)")
# Alternative: mount drive and set path
from google.colab import drive
drive.mount('/content/drive')

#If you uploaded the files manually
try:
    train = pd.read_csv('train.csv')
    test = pd.read_csv('test.csv')
    sample = pd.read_csv('sample_submission.csv')
    print("✅ Files loaded successfully!")
except FileNotFoundError:
    print("❌ Files not found. Attempting to unzip uploaded files.")
    # If you prefer to upload interactively
    uploaded = files.upload()
    for fn in uploaded.keys():
        if fn.endswith('.zip'):
            print(f"Unzipping {fn}...")
            with zipfile.ZipFile(fn, 'r') as zip_ref:
                zip_ref.extractall('.')
            print("Unzipping complete.")
        else:
            print(f"Uploaded file {fn} is not a zip file, skipping unzip.")

    # Try loading again after unzipping
    try:
        train = pd.read_csv('train.csv')
        test = pd.read_csv('test.csv')
        sample = pd.read_csv('sample_submission.csv')
        print("✅ Files loaded successfully after unzipping!")
    except FileNotFoundError:
        print("❌ train.csv or test.csv still not found after unzipping. Please ensure they are in the zip file or upload them directly.")

# %%
print(f"Train shape: {train.shape}, Test shape: {test.shape}")
train.head()

# 2. Data Overview & Preprocessing Setup


# Combine train and test for unified feature engineering (excluding SalePrice)
target = 'SalePrice'
train_target = train[target].copy()
train_ids = train['Id'].copy()
test_ids = test['Id'].copy()

# Drop target and Id from features (Id is not predictive)
train_feat = train.drop(columns=[target, 'Id'])
test_feat = test.drop(columns=['Id'])

all_data = pd.concat([train_feat, test_feat], axis=0, ignore_index=True)
print(f"Combined data shape: {all_data.shape}")

# 3. Domain-Aware Missing Value Handling

# Based on data description, `NA` often means "absence" (e.g., no basement, no garage, no pool).

# Define groups of features with specific imputation strategies

# Features where NA means "None" or "No" (categorical)
none_cats = ['Alley', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1',
             'BsmtFinType2', 'FireplaceQu', 'GarageType', 'GarageFinish',
             'GarageQual', 'GarageCond', 'PoolQC', 'Fence', 'MiscFeature', 'KitchenQual']

# For these, fill with 'None' (or 'No')
for col in none_cats:
    if col in all_data.columns:
        all_data[col] = all_data[col].fillna('None')

# Numerical features where NA means 0 (absence)
zero_num = ['MasVnrArea', 'BsmtFinSF1', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF',
            'BsmtFullBath', 'BsmtHalfBath', 'GarageArea', 'GarageCars',
            'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', '3SsnPorch',
            'ScreenPorch', 'PoolArea', 'MiscVal']

for col in zero_num:
    if col in all_data.columns:
        all_data[col] = all_data[col].fillna(0)

# LotFrontage: fill with median per Neighborhood (strong correlation)
if 'LotFrontage' in all_data.columns:
    all_data['LotFrontage'] = all_data.groupby('Neighborhood')['LotFrontage'].transform(
        lambda x: x.fillna(x.median())
    )
    # If still NaN (Neighborhood with all NaN), use global median
    all_data['LotFrontage'] = all_data['LotFrontage'].fillna(all_data['LotFrontage'].median())

# MasVnrType: fill with 'None' (matches zero area)
if 'MasVnrType' in all_data.columns:
    all_data['MasVnrType'] = all_data['MasVnrType'].fillna('None')

# Electrical: only one missing in training set, fill with mode
if 'Electrical' in all_data.columns:
    all_data['Electrical'] = all_data['Electrical'].fillna(all_data['Electrical'].mode()[0])

# GarageYrBlt: if missing, assume no garage -> 0
if 'GarageYrBlt' in all_data.columns:
    all_data['GarageYrBlt'] = all_data['GarageYrBlt'].fillna(0)

# Functional: fill with 'Typ' (typical)
if 'Functional' in all_data.columns:
    all_data['Functional'] = all_data['Functional'].fillna('Typ')

# Utilities: almost all 'AllPub', fill with that
if 'Utilities' in all_data.columns:
    all_data['Utilities'] = all_data['Utilities'].fillna('AllPub')

# MSZoning: fill with mode
if 'MSZoning' in all_data.columns:
    all_data['MSZoning'] = all_data['MSZoning'].fillna(all_data['MSZoning'].mode()[0])

# SaleType: fill with mode
if 'SaleType' in all_data.columns:
    all_data['SaleType'] = all_data['SaleType'].fillna(all_data['SaleType'].mode()[0])

# Exterior1st, Exterior2nd: fill with mode
for col in ['Exterior1st', 'Exterior2nd']:
    if col in all_data.columns:
        all_data[col] = all_data[col].fillna(all_data[col].mode()[0])

print("Missing values after imputation:\n", all_data.isnull().sum().sum())

#to check for missing values after imputation (like kitchneQual)
missing_after_imputation = all_data.isnull().sum()
missing_after_imputation = missing_after_imputation[missing_after_imputation > 0]
print("Columns with missing values after imputation:\n", missing_after_imputation)

# 4. Advanced Feature Engineering


# 4.1 Combined living area (total above ground + basement)
all_data['TotalSF'] = all_data['TotalBsmtSF'] + all_data['1stFlrSF'] + all_data['2ndFlrSF']

# 4.2 Total bathrooms (full + half, above grade + basement)
all_data['TotalBath'] = (all_data['FullBath'] + 0.5*all_data['HalfBath'] +
                         all_data['BsmtFullBath'] + 0.5*all_data['BsmtHalfBath'])

# 4.3 Total porch area
all_data['TotalPorch'] = (all_data['OpenPorchSF'] + all_data['EnclosedPorch'] +
                          all_data['3SsnPorch'] + all_data['ScreenPorch'])

# 4.4 Age features
all_data['HouseAge'] = all_data['YrSold'] - all_data['YearBuilt']
all_data['RemodAge'] = all_data['YrSold'] - all_data['YearRemodAdd']
all_data['IsRemodelled'] = (all_data['YearRemodAdd'] != all_data['YearBuilt']).astype(int)

# 4.5 Garage age (if built)
all_data['GarageAge'] = np.where(all_data['GarageYrBlt'] > 0,
                                 all_data['YrSold'] - all_data['GarageYrBlt'], 0)

# 4.6 Quality interaction (overall quality * condition)
all_data['OverallQualCond'] = all_data['OverallQual'] * all_data['OverallCond']

# 4.7 Has features (binary flags)
all_data['HasBasement'] = (all_data['TotalBsmtSF'] > 0).astype(int)
all_data['HasGarage'] = (all_data['GarageArea'] > 0).astype(int)
all_data['HasFireplace'] = (all_data['Fireplaces'] > 0).astype(int)
all_data['HasPool'] = (all_data['PoolArea'] > 0).astype(int)

# 4.8 Simplify high-cardinality categoricals (group rare categories)
def group_rare(series, threshold=0.01):
    """Group categories with frequency < threshold into 'Other'"""
    counts = series.value_counts(normalize=True)
    rare = counts[counts < threshold].index
    return series.replace(rare, 'Other')

for col in ['Neighborhood', 'Exterior1st', 'Exterior2nd']:
    if col in all_data.columns:
        all_data[col] = group_rare(all_data[col], threshold=0.01)

# 4.9 Month & Year features (cyclical encoding)
all_data['MoSin'] = np.sin(2 * np.pi * all_data['MoSold'] / 12)
all_data['MoCos'] = np.cos(2 * np.pi * all_data['MoSold'] / 12)
# YrSold can be kept as is, or also cyclical (but year is linear)

# 4.10 Lot shape squared (irregularity impact)
all_data['IsIrregularLot'] = (all_data['LotShape'] != 'Reg').astype(int)

# 4.11 Neighborhood target encoding (will be done inside CV to avoid leakage)
# We'll compute mean SalePrice per neighborhood from training only and map
# But we need to do it after splitting, so we'll create a placeholder.
# We'll implement this as a transformer in the modeling phase.

# 4.12 Drop redundant or constant columns
cols_to_drop = ['Utilities']  # almost all 'AllPub'
all_data.drop(columns=[c for c in cols_to_drop if c in all_data.columns], inplace=True, errors='ignore')

print(f"Feature engineering done. New shape: {all_data.shape}")

# Define the full list of features after engineering
# These are the columns in all_data that will be used for modeling
features = all_data.columns.tolist()
print(f"Total features for modeling: {len(features)}")

'''# -----------------------------------------------------------------------------
# 2. EXPLORATORY DATA ANALYSIS (EDA) & FEATURE ENGINEERING
# -----------------------------------------------------------------------------
# 2.1 Target variable distribution
plt.figure(figsize=(12, 5))
plt.subplot(1, 2, 1)
sns.histplot(df['SalePrice'], kde=True)
plt.title('SalePrice Distribution (Raw)')
plt.subplot(1, 2, 2)
sns.histplot(np.log1p(df['SalePrice']), kde=True)
plt.title('Log(SalePrice) Distribution')
plt.tight_layout()
plt.show()

print(f"\nTarget statistics:\n{df['SalePrice'].describe()}")

# 2.2 Missing values audit (on full dataset, but decisions will be made on train split)
missing = df.isnull().sum()
missing = missing[missing > 0].sort_values(ascending=False)
print("\nMissing values per column (full dataset):")
print(missing)

# 2.3 Feature engineering – create powerful new features
# These are based on domain knowledge and common practice in Ames competition
df['TotalSF'] = df['GrLivArea'] + df['TotalBsmtSF'].fillna(0)       # total usable square footage
df['TotalBaths'] = (df['FullBath'] + 0.5*df['HalfBath'] +
                    df['BsmtFullBath'] + 0.5*df['BsmtHalfBath'])    # total bathroom count
df['Age'] = df['YrSold'] - df['YearBuilt']                           # age at sale
df['RemodAge'] = df['YrSold'] - df['YearRemodAdd']                   # years since remodel
df['HasBasement'] = (df['TotalBsmtSF'] > 0).astype(int)
df['HasGarage'] = (df['GarageArea'] > 0).astype(int)
df['TotalPorchSF'] = (df['OpenPorchSF'] + df['EnclosedPorch'] +
                      df['3SsnPorch'] + df['ScreenPorch'])

# 2.4 Select top 12 features (after correlation analysis & domain knowledge)
# Numeric features: correlate with SalePrice, high importance from literature
numeric_candidates = ['OverallQual', 'GrLivArea', 'TotalSF', 'TotalBaths',
                      'YearBuilt', 'Age', 'Fireplaces', 'GarageCars',
                      'GarageArea', 'TotalPorchSF']

# Categorical features: known to have strong influence
categorical_candidates = ['Neighborhood', 'KitchenQual', 'MSZoning']

# Final feature set (12 features exactly)
features = numeric_candidates + categorical_candidates
print("\nSelected features (12):", features)

# Check missing values in selected features (on full data for diagnosis)
missing_selected = df[features].isnull().sum()
print("\nMissing in selected features (full data):")
print(missing_selected[missing_selected > 0])

# 2.5 Visualize correlations with target
plt.figure(figsize=(10, 8))
numeric_features = [f for f in features if f in df.select_dtypes(include=np.number).columns]
corr = df[numeric_features + ['SalePrice']].corr()
sns.heatmap(corr[['SalePrice']].sort_values(by='SalePrice', ascending=False),
            annot=True, cmap='coolwarm', fmt='.2f')
plt.title('Correlation of Numeric Features with SalePrice')
plt.tight_layout()
plt.show()'''

# -----------------------------------------------------------------------------
# 3. TRAIN / VALIDATION / TEST SPLIT (NO LEAKAGE)
# -----------------------------------------------------------------------------

# Separate processed all_data back into train and test sets
X = all_data.iloc[:len(train_target)][features] # Features for training (from original train set)
X_test_final = all_data.iloc[len(train_target):][features] # Features for final prediction (original test set)
y = train_target # Target variable for training

# First split: train (70%) and temp (30%)
X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.3, random_state=42)
# Second split: temp into validation (15%) and test (15%)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42)

print(f"\nSplit sizes: Train={len(X_train)}, Val={len(X_val)}, Test={len(X_test)}")
print(f"Shape of X_train: {X_train.shape}, y_train: {y_train.shape}")
print(f"Shape of X_val: {X_val.shape}, y_val: {y_val.shape}")
print(f"Shape of X_test: {X_test.shape}, y_test: {y_test.shape}")
print(f"Shape of X_test_final (for submission): {X_test_final.shape}")

# -----------------------------------------------------------------------------
# 4. PREPROCESSING PIPELINE (FIT ONLY ON TRAIN)
# -----------------------------------------------------------------------------
# Identify columns by type from the actual training data (X_train)
numeric_cols = X_train.select_dtypes(include=np.number).columns.tolist()
categorical_cols = X_train.select_dtypes(include='object').columns.tolist()

# 4.1 Define ordinal categories for KitchenQual (typical Ames order)
# Check if KitchenQual is in categorical_cols before defining the order
kitchen_qual_order = ['Po', 'Fa', 'TA', 'Gd', 'Ex']
ordinal_features = []
if 'KitchenQual' in categorical_cols:
    ordinal_mappings = {'KitchenQual': kitchen_qual_order}
    ordinal_features.append('KitchenQual')
    categorical_cols.remove('KitchenQual') # Remove from categorical to avoid double processing

# For nominal categoricals: all remaining categorical columns
nominal_cols = categorical_cols

# 4.2 Missing value imputation strategies (justified)
# Numeric: median imputation (robust to outliers)
# Ordinal: most frequent (mode) because missing is rare; treat as 'typical' quality
# Nominal: most frequent (mode) – missing values are rare and imputing with mode preserves distribution
numeric_imputer = SimpleImputer(strategy='median')
ordinal_imputer = SimpleImputer(strategy='most_frequent') # Used for KitchenQual if it exists
nominal_imputer = SimpleImputer(strategy='most_frequent')

# 4.3 Scaling: StandardScaler for numeric features (tree models don't need it, but good practice for consistency)
scaler = StandardScaler()

# 4.4 Encoding:
# Ordinal: use OrdinalEncoder with custom categories
# Only create ordinal_encoder if ordinal_features is not empty
if ordinal_features:
    ordinal_encoder = OrdinalEncoder(categories=[ordinal_mappings['KitchenQual']],
                                      handle_unknown='use_encoded_value', unknown_value=-1)
else:
    ordinal_encoder = None # Or handle this case appropriately

# Nominal: OneHotEncoder (drop first to avoid multicollinearity)
nominal_encoder = OneHotEncoder(drop='first', sparse_output=False, handle_unknown='ignore')

# 4.5 Build ColumnTransformer
# Only include ordinal processing if ordinal_features is not empty
transformers = [
    ('num', Pipeline([('impute', numeric_imputer), ('scale', scaler)]), numeric_cols)
]
if ordinal_features and ordinal_encoder is not None:
    transformers.append(('ord', Pipeline([('impute', ordinal_imputer), ('encode', ordinal_encoder)]), ordinal_features))
if nominal_cols:
    transformers.append(('nom', Pipeline([('impute', nominal_imputer), ('encode', nominal_encoder)]), nominal_cols))

preprocessor = ColumnTransformer(transformers, remainder='passthrough') # 'passthrough' for columns not explicitly transformed

# Test preprocessor on train (no leakage)
X_train_processed = preprocessor.fit_transform(X_train)
print(f"\nProcessed training data shape: {X_train_processed.shape}")

# -----------------------------------------------------------------------------
# 5. MODEL PIPELINES (TWO SWAPPABLE MODELS)
# -----------------------------------------------------------------------------
# Model 1: Random Forest
rf_pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('regressor', RandomForestRegressor(random_state=42, n_jobs=-1))
])

# Model 2: Gradient Boosting
gb_pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('regressor', GradientBoostingRegressor(random_state=42))
])

# -----------------------------------------------------------------------------
# 6. HYPERPARAMETER TUNING (USING TRAIN + VALIDATION, BUT CV ON TRAIN)
# -----------------------------------------------------------------------------
# To avoid overfitting the validation set, we perform cross-validation on the training set
# and then evaluate each tuned model on the validation set. We'll choose the best model based on validation RMSE.

# Parameter grids
param_grid_rf = {
    'regressor__n_estimators': [100, 200],
    'regressor__max_depth': [10, 20, None],
    'regressor__min_samples_split': [2, 5]
}

param_grid_gb = {
    'regressor__n_estimators': [100, 200],
    'regressor__learning_rate': [0.05, 0.1],
    'regressor__max_depth': [3, 5]
}

# Grid search with 3-fold CV on training set
grid_rf = GridSearchCV(rf_pipeline, param_grid_rf, cv=3, scoring='neg_mean_squared_error',
                       n_jobs=-1, verbose=1)
grid_gb = GridSearchCV(gb_pipeline, param_grid_gb, cv=3, scoring='neg_mean_squared_error',
                       n_jobs=-1, verbose=1)

print("\nTraining Random Forest with GridSearchCV...")
grid_rf.fit(X_train, y_train)

print("\nTraining Gradient Boosting with GridSearchCV...")
grid_gb.fit(X_train, y_train)

# Best estimators
best_rf = grid_rf.best_estimator_
best_gb = grid_gb.best_estimator_

print("\nBest Random Forest params:", grid_rf.best_params_)
print("Best Gradient Boosting params:", grid_gb.best_params_)

# -----------------------------------------------------------------------------
# 7. EVALUATION ON VALIDATION SET (MODEL COMPARISON)
# -----------------------------------------------------------------------------
def evaluate_model(model, X, y, name="Model"):
    y_pred = model.predict(X)
    rmse = np.sqrt(mean_squared_error(y, y_pred))
    mae = mean_absolute_error(y, y_pred)
    r2 = r2_score(y, y_pred)
    print(f"{name} - RMSE: ${rmse:,.0f}, MAE: ${mae:,.0f}, R2: {r2:.4f}")
    return rmse, mae, r2

print("\n--- Validation Set Performance ---")
evaluate_model(best_rf, X_val, y_val, "Random Forest (tuned)")
evaluate_model(best_gb, X_val, y_val, "Gradient Boosting (tuned)")

# Choose best model based on validation RMSE
val_rf_rmse = np.sqrt(mean_squared_error(y_val, best_rf.predict(X_val)))
val_gb_rmse = np.sqrt(mean_squared_error(y_val, best_gb.predict(X_val)))

if val_rf_rmse < val_gb_rmse:
    best_model = best_rf
    best_model_name = "Random Forest"
else:
    best_model = best_gb
    best_model_name = "Gradient Boosting"

print(f"\nBest model on validation: {best_model_name} (RMSE: ${min(val_rf_rmse, val_gb_rmse):,.0f})")

# -----------------------------------------------------------------------------
# 8. TRAIN VS VALIDATION SCORES (FOR BEST MODEL)
# -----------------------------------------------------------------------------
print("\n--- Train vs Validation Scores (Best Model) ---")
train_rmse, train_mae, train_r2 = evaluate_model(best_model, X_train, y_train, "Train")
val_rmse, val_mae, val_r2 = evaluate_model(best_model, X_val, y_val, "Validation")

# -----------------------------------------------------------------------------
# 9. FINAL EVALUATION ON TEST SET (EXACTLY ONCE)
# -----------------------------------------------------------------------------
print("\n--- Test Set Performance (Final, One-Time Evaluation) ---")
test_rmse, test_mae, test_r2 = evaluate_model(best_model, X_test, y_test, "Test")

# -----------------------------------------------------------------------------
# 10. SERIALIZE THE BEST MODEL
# -----------------------------------------------------------------------------
model_filename = f"best_ames_model_{best_model_name.lower().replace(' ', '_')}.pkl"
joblib.dump(best_model, model_filename)
print(f"\nBest model saved as '{model_filename}'")

# -----------------------------------------------------------------------------
# 11. SUMMARY REPORT
# -----------------------------------------------------------------------------
print("\n" + "="*60)
print("FINAL PIPELINE SUMMARY")
print("="*60)
print(f"Selected features ({len(features)}): {features}")
print(f"Train/Val/Test sizes: {len(X_train)} / {len(X_val)} / {len(X_test)}")
print(f"Missing value handling: numeric→median, categorical→mode (fit on train only)")
print(f"Encoding: Ordinal(KitchenQual if present), OneHot(other nominal categoricals)")
print(f"Scaling: StandardScaler on numeric features")
print(f"Best model: {best_model_name}")
print(f"Test RMSE: ${test_rmse:,.0f}")
print(f"Test MAE: ${test_mae:,.0f}")
print(f"Test R²: {test_r2:.4f}")
print("="*60)

# Optional: Feature importance (if model supports it)
if hasattr(best_model.named_steps['regressor'], 'feature_importances_'):
    # Get feature names after preprocessing
    preprocessor = best_model.named_steps['preprocessor']

    all_feature_names = []

    # Numeric features
    all_feature_names.extend(numeric_cols)

    # Ordinal feature (KitchenQual) if it was processed
    if 'ord' in preprocessor.named_transformers_ and ordinal_features:
        ord_features_encoded = preprocessor.named_transformers_['ord'].named_steps['encode'].get_feature_names_out(ordinal_features).tolist()
        all_feature_names.extend(ord_features_encoded)

    # Nominal features after OneHot
    if 'nom' in preprocessor.named_transformers_ and nominal_cols:
        ohe = preprocessor.named_transformers_['nom'].named_steps['encode']
        nom_features_encoded = ohe.get_feature_names_out(nominal_cols).tolist()
        all_feature_names.extend(nom_features_encoded)

    # Handle passthrough columns if any
    # The 'remainder' will be at the end of the transformed array if it's 'passthrough'
    # The names correspond to columns in X_train that were not explicitly transformed
    # For this specific setup, we expect all columns to be handled, but defensively:
    if preprocessor.remainder == 'passthrough':
        transformed_columns_set = set(numeric_cols + (ordinal_features if ordinal_features else []) + (nominal_cols if nominal_cols else []))
        passthrough_cols = [col for col in X_train.columns if col not in transformed_columns_set]
        all_feature_names.extend(passthrough_cols)

    importances = best_model.named_steps['regressor'].feature_importances_

    # Ensure the number of feature importances matches the number of feature names
    if len(importances) == len(all_feature_names):
        feat_imp = pd.Series(importances, index=all_feature_names).sort_values(ascending=False)
        plt.figure(figsize=(10, 6))
        feat_imp.head(15).plot(kind='bar')
        plt.title(f'Feature Importances - {best_model_name}')
        plt.tight_layout()
        plt.show()
    else:
        print("Warning: Mismatch between number of feature importances and feature names. Cannot plot feature importances.")
        print(f"Number of importances: {len(importances)}, Number of names: {len(all_feature_names)}")